import type { NextApiRequest, NextApiResponse } from "next";
import { handleGenerateDailyArchive } from "../../../server/routes/autoGenerateDaily";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  return handleGenerateDailyArchive(req as any, res as any);
}
