import type { NextApiRequest, NextApiResponse } from "next";
import { handleGenerateDailyArchive } from "../../../server/routes/autoGenerateDaily";
import { runExpressHandler } from "../../../server/lib/nextApiAdapter";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  return runExpressHandler(handleGenerateDailyArchive, req, res);
}
