[build]
command = "corepack pnpm build"
functions = "netlify/functions"
publish = "out"


[functions]
node_bundler = "esbuild"
[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"

[[redirects]]
force = false
from = "/*"
status = 200
to = "/index.html"
