import "dotenv/config";
import express from "express";
import cors from "cors";
import cron from "node-cron";
import { handleDemo } from "./routes/demo";

import { handleSiteDetails } from "./routes/siteDetails";
import { handleGenerateArchive } from "./routes/generateArchive";
import { generateDailyArchive, handleGenerateDailyArchive } from "./routes/autoGenerateDaily";
import { handleShingoChat } from "./routes/shingoChat";

export function createServer() {
  const app = express();

  // Middleware
  app.use(cors());
  app.use(express.json());
  app.use(express.urlencoded({ extended: true }));

  // Example API routes
  app.get("/api/ping", (_req, res) => {
    const ping = process.env.PING_MESSAGE ?? "ping";
    res.json({ message: ping });
  });

  app.get("/api/site-details", handleSiteDetails);
  app.post("/api/generate-archive", handleGenerateArchive);
  app.post("/api/shingo-chat", handleShingoChat);
  
  // Endpoint to manually trigger or via external cron
  app.post("/api/cron/generate-daily", handleGenerateDailyArchive);

  app.get("/api/demo", handleDemo);

  // Setup Daily Cron Job directly in code
  // This runs every day at 12:00 AM (midnight)
  cron.schedule("0 0 * * *", () => {
    console.log("CRON: Triggering daily archive generation...");
    generateDailyArchive();
  });

  return app;
}
